FROM arm64v8/ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive 
# Обновляем пакеты и устанавливаем необходимые зависимости
RUN apt clean && apt-get update && \
    apt-get install -y \
    openssh-server \
    cmake \
    git \
    gcc-10 \
    g++ \
    gcc \
    clang \
    python3 \
    pkg-config \
    libzmq3-dev \
    libelf-dev \
    python \
    libyaml-cpp-dev \
    nlohmann-json3-dev \
    g++-10 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ARG YAML_VERSION=0.7.0
WORKDIR /opt
RUN  touch /etc/ssh/ssh_known_hosts; \
     chmod 600 /etc/ssh/ssh_known_hosts; \
     chown root:root /etc/ssh/ssh_known_hosts && \
     sed -i /^StrictHostKeyChecking/d /etc/ssh/ssh_config; \
     echo StrictHostKeyChecking no >> /etc/ssh/ssh_config  && \
     ssh-keyscan bb.niias > /etc/ssh/ssh_known_hosts
RUN --mount=type=ssh git clone -b release  --depth 1 --recursive ssh://git@bb.niias:7999/elsd/zcm.git
RUN cd /opt/zcm \
                    && cd /opt/zcm \
    && ./waf configure \
                --use-inproc \
                --use-ipc \
                --use-udpm \
                --use-udpd \
                --use-udp \
                --use-serial \
                --use-zmq \
                --use-third-party \
                --use-elf \
    &&./waf build \
    && ./waf install \
    && rm -rf /opt/zcm
RUN --mount=type=ssh git clone -b master --depth 1 --recursive ssh://git@bb.niias:7999/tool/nlohmann_json.git
RUN cd /opt/nlohmann_json \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j 3 \
    && make install \
    && rm -rf /opt/nlohmann_json

RUN ldconfig
